default_settings = ""
debug = false
longitude = 6.57
data_dir = "/net/node105/data/users/lofareor/mertens/fromnode100_12feb2024/ncp_np6_red2"

[worker]
nodes = 'node[110-114]'
max_concurrent = 1
env_file = "~/.activate_pspipe_test.sh"

[merge_ms]
apply_aoflagger = true
data_col = "CORRECTED_DATA"
obs_id_out_suffix = "flagged"
blmin = 0
blmax = 1000
flag_baselines = ""
avg_timestep = 1
time_start_index = 0
time_end_index = 0

[ssins]
apply_ssins = true
n_time_avg = [ 1, 4, 8,]
percentage_freq_full_flag = 0.4
percentage_time_full_flag = 0.4
time_freq_threshold = 0.6
baseline_threshold = 0.75
snapshot_threshold = 0.5

[vis_to_sph]
obs_id_out_suffix = "sph"
pre_flag = ""

[vis_cube]
fov = 4
umin = 50
umax = 250
win_fct = "(tukey,0.2)"

[combine]
obs_id_out_prefix = "001"
scale_with_noise = true
weights_mode = "full"
inhomogeneous = false
pre_flag = "config/flagger_pre_combine.parset"

[power_spectra]
eor_bin_list = "config/eor_bins_hba.parset"
ps_config = "config/ps_config_hba.parset"
flagger = "config/flagger.parset"

[gpr]
config_i = "config/gpr_config_hba.parset"
config_v = "config/gpr_config_v.parset"

[image]
data_col = "CORRECTED_DATA"
channels_out = "all"
time_start_index = 0
time_end_index = 0
lst_bins = []
stokes = "IV"
split_even_odd = true
weight = "natural"
umin = 50
umax = 500
scale = "0.5amin"
size = "512 512"
name = "default"

[ssins.nsigmas]
1 = [ 8, 5, 5,]
4 = [ 8, 5, 5,]
8 = [ 8, 5, 5,]
